title: Xuanzi Guo's Homepage
page-top-title: Xuanzi Guo
top-section-bg-text: Robot Science
home-subtitle: Xuanzi Guo&ensp;|&ensp;郭炫孜
copyright-text: '&copy; Xuanzi Guo 2024-2025. All Rights Reserved.'
