title: Jovan Zhao's Homepage
page-top-title: Jovan Zhao
top-section-bg-text: Computer Science
backgrounds:
  - static/assets/background/background_0.jpeg
  - static/assets/background/background_1.jpeg
background-interval-ms: 7000
background-overlay: 0.52
copyright-text: '&copy; Jovan Zhao 2023-2026. All Rights Reserved.'
github-link:
  text: Github
  href: https://github.com/JovanZhaoScorpiO
license-link:
  text: Zhaocense
  href: https://github.com/JovanZhaoScorpiO/JovanZhaoScorpiO.github.io/blob/main/LICENSE
sections:
  - id: home
    nav: HOME
    title: Jovan Zhao&ensp;|&ensp;赵卓凡
    href: '#page-top' # Default to '#<id>' if not specified
  - id: publications
    nav: PUBLICATIONS
    title: PUBLICATIONS
    icon: bi-file-text-fill
  - id: awards
    nav: AWARDS
    title: AWARDS
    icon: bi-award-fill
