title: WINGs 2026's Homepage
page-top-title: WINGs 2026
top-section-bg-text: Women in Number Theory and Geometry Spring Retreat 2026
home-subtitle: Dates: 13-16th April, Location: [...], UK
copyright-text: '&copy; Sen Li 2023-2025. All Rights Reserved.'
