title: Shaowei Wang's Homepage
page-top-title: Shaowei Wang
top-section-bg-text: Economics
home-subtitle: Shaowei Wang&ensp;|&ensp;王少伟
copyright-text: '&copy; Shaowei Wang 2024-2025. All Rights Reserved.'
